# Generated by Django 5.1 on 2024-08-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_rename_reminders_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='name',
            new_name='title',
        ),
    ]
