# Generated by Django 5.1 on 2024-08-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_rename_name_reminder_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='description',
        ),
    ]
